<a href="https://colab.research.google.com/github/sahilparmar4/Goeduhub-Assignments/blob/main/Goeduhub_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Import the numpy package under the name np and Print the numpy version and the configuration**

In [ ]:
import numpy as np
print("Numpy current version:", np.__version__)
print("Numpy configuration:", np.__config__)

Numpy current version: 1.19.5
Numpy configuration: <module 'numpy.__config__' from '/usr/local/lib/python3.7/dist-packages/numpy/__config__.py'>


**2. Create a null vector of size 10**

In [ ]:
print("Null vector of size 10:", np.empty(10))

Null vector of size 10: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print("1d array:", a)
print()
print("Type of array:", type(a))
print()
print("Data type in array elements:", a.dtype)

1d array: [1 2 3 4 5 6 7]

Type of array: <class 'numpy.ndarray'>

Data type in array elements: int64


**4. How to find number of dimensions, bytes per element and bytes of memory used?**

In [ ]:
print("Dimensions of array:", a.ndim)

import sys
print("Total bytes:", sys.getsizeof(a))
print("Bytes per element:", sys.getsizeof(len(a)))

Dimensions of array: 1
Total bytes: 152
Bytes per element: 28


**5. Create a null vector of size 10 but the fifth value which is 1**

In [ ]:
s = np.zeros(10)
print(s)
s[4]= 1
print("After changing it to 5th element: ", s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After changing it to 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**6. Create a vector with values ranging from 10 to 49**

In [ ]:
a = np.arange(10, 49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**7. Reverse a vector (first element becomes last)**

In [ ]:
a = a[::-1]
print(a)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**8. Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
a = np.arange(0, 9)
print(a)
print("3 * 3 array: \n", a.reshape(3, 3))

[0 1 2 3 4 5 6 7 8]
3 * 3 array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**9. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [ ]:
a = [1, 2, 0, 0, 4, 0]
print("Indices of non zero elements:", np.nonzero(a))

Indices of non zero elements: (array([0, 1, 4]),)


**10. Create a 3x3 identity matrix**

In [ ]:
identity = np.identity(3)
print("I3:\n", identity)

I3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**11. Create a 3x3x3 array with random values**

In [ ]:
random = np.random.random((3, 3))
print("R3:\n", random)

R3:
 [[0.78235321 0.66010169 0.21749345]
 [0.62207198 0.95585855 0.44139432]
 [0.44027814 0.11277937 0.67250444]]


**12. Create a 10x10 array with random values and find the minimum and maximum values**

In [ ]:
random_10 = np.random.random((10, 10))
print("R10:\n", random_10)
print("Maximum value:", random_10.max())
print("Minimum value:", random_10.min())

R10:
 [[0.84018497 0.9199264  0.5763538  0.95707136 0.02633945 0.78151549
  0.77971374 0.67890942 0.8940941  0.79060932]
 [0.77582743 0.26155105 0.99933929 0.57710828 0.71702514 0.45615277
  0.63368453 0.5455681  0.56502306 0.72052576]
 [0.31008152 0.48316631 0.24511412 0.00849619 0.31334466 0.04560287
  0.03412257 0.63284466 0.37349175 0.04858599]
 [0.73628603 0.39065273 0.06576624 0.34930086 0.45703137 0.01799795
  0.50991984 0.02465647 0.56571902 0.9680785 ]
 [0.87826809 0.4305752  0.35659838 0.21030152 0.10397677 0.07695085
  0.99767044 0.80032645 0.96127206 0.01177039]
 [0.67172076 0.40954802 0.18085181 0.36790432 0.06420822 0.37586113
  0.6677465  0.51580426 0.67525997 0.73078913]
 [0.60437717 0.19714424 0.00967589 0.65257589 0.01467421 0.02018858
  0.28995432 0.1399231  0.77281328 0.87315798]
 [0.2930877  0.42418199 0.30986847 0.5292331  0.89546433 0.27535301
  0.4256233  0.91721377 0.14311411 0.7425629 ]
 [0.86977433 0.50262431 0.1125091  0.92589141 0.26676756 0.15826981
  0.04

**13. Create a random vector of size 30 and find the mean value**

In [ ]:
vector_30 = np.random.random(30)
print("V30:\n", vector_30)
print("Mean:", vector_30.mean())

V30:
 [0.92336976 0.43829071 0.52645556 0.47234176 0.47560241 0.27333761
 0.23015708 0.84938864 0.75802618 0.09044788 0.85347112 0.3914411
 0.95414919 0.81856688 0.1804604  0.62255555 0.5450969  0.86403022
 0.3942209  0.41437721 0.64127395 0.55262749 0.81198504 0.72466252
 0.44364905 0.29737734 0.91106939 0.64968461 0.20682698 0.5515167 ]
Mean: 0.5622153376846373


**14. Create a 2D array with 1 on the border and 0 inside**

In [ ]:
s = np.ones((5, 5))
print(s)
s[1:-1, 1:-1] = 0
print(s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**15. How to add a border (filled with 0's) around an existing array?**

In [ ]:
s = np.zeros((5, 5))
print(s)
s[1:-1, 1:-1] = 1
print(s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]]) 
print("Array:", a)
print("Get 13:", a[1][-2])
print("First row only:", a[0])
print("Third column only:", a[:, 4])
print("2, 4, 6:", a[0, 1:7:2])
a[1, -2] = 20 
print("13 updated by 20:", a)

Array: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Get 13: 13
First row only: [1 2 3 4 5 6 7]
Third column only: [ 5 12]
2, 4, 6: [2 4 6]
13 updated by 20: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**17. How to Convert a 1D array to a 2D array with 2 rows**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("2D array with 2 rows:\n", np.reshape(arr, (2, 3)))

2D array with 2 rows:
 [[1 2 3]
 [4 5 6]]


**18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**

Input:

a = np.array([1,2,3])`

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1, 2, 3])
print("Pattern:\n", np.r_[np.repeat(a, 3), np.tile(a, 3)])

Pattern:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**19. Write a program to show how Numpy taking less memory compared to Python List?**

In [ ]:
# Lists
l = range(1000)

import sys
a = 10
print("Memory taken by a list:")
print(sys.getsizeof(a)*len(l))
print()

# nd arrays
print("Memory taken by an Array:")
s = np.arange(1000)
print(s.size*s.itemsize)

Memory taken by a list:
28000

Memory taken by an Array:
8000


**20. Write a program to show how Numpy taking less time compared to Python List?**

In [ ]:
import time

#List
size = 1000000
l1 = range(size)
l2 = range(size)
print(l1)
print(l2)

#Array
n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result = n1 + n2
print((time.time()-start)*1000)

range(0, 1000000)
range(0, 1000000)
2.276182174682617
